import { Topic, BaseQuestion } from './types';

export const topics: Topic[] = [
  {
    id: 'speed',
    name: 'Скоростной режим',
    nameUz: 'Tezlik rejimi',
    icon: '🚗',
    description: 'Ограничения скорости на различных дорогах',
    descriptionUz: 'Turli yo\'llarda tezlik cheklovlari',
  },
  {
    id: 'signs-warning',
    name: 'Предупреждающие знаки',
    nameUz: 'Ogohlantiruvchi belgilar',
    icon: '⚠️',
    description: 'Знаки, предупреждающие об опасности',
    descriptionUz: 'Xavf haqida ogohlantiradigan belgilar',
  },
  {
    id: 'signs-prohibition',
    name: 'Запрещающие знаки',
    nameUz: 'Taqiqlovchi belgilar',
    icon: '🚫',
    description: 'Знаки, запрещающие определённые действия',
    descriptionUz: 'Ma\'lum harakatlarni taqiqlaydigan belgilar',
  },
  {
    id: 'signs-mandatory',
    name: 'Предписывающие знаки',
    nameUz: 'Buyruq belgilari',
    icon: '➡️',
    description: 'Знаки, указывающие обязательные направления',
    descriptionUz: 'Majburiy yo\'nalishlarni ko\'rsatadigan belgilar',
  },
  {
    id: 'signs-info',
    name: 'Информационные знаки',
    nameUz: 'Axborot belgilari',
    icon: 'ℹ️',
    description: 'Знаки, информирующие водителя',
    descriptionUz: 'Haydovchini xabardor qiluvchi belgilar',
  },
  {
    id: 'marking',
    name: 'Дорожная разметка',
    nameUz: 'Yo\'l chiziqlari',
    icon: '🛣️',
    description: 'Горизонтальная и вертикальная разметка',
    descriptionUz: 'Gorizontal va vertikal chiziqlar',
  },
  {
    id: 'traffic-lights',
    name: 'Сигналы светофора',
    nameUz: 'Svetofor signallari',
    icon: '🚦',
    description: 'Значение сигналов светофора и регулировщика',
    descriptionUz: 'Svetofor va tartibga soluvchi signallari ma\'nosi',
  },
  {
    id: 'intersections',
    name: 'Проезд перекрёстков',
    nameUz: 'Chorrahalardan o\'tish',
    icon: '🔀',
    description: 'Правила проезда различных перекрёстков',
    descriptionUz: 'Turli chorrahalardan o\'tish qoidalari',
  },
  {
    id: 'overtaking',
    name: 'Обгон и опережение',
    nameUz: 'Quvib o\'tish',
    icon: '🏎️',
    description: 'Правила выполнения обгона',
    descriptionUz: 'Quvib o\'tish qoidalari',
  },
  {
    id: 'parking',
    name: 'Остановка и стоянка',
    nameUz: 'To\'xtash va turish',
    icon: '🅿️',
    description: 'Правила остановки и стоянки',
    descriptionUz: 'To\'xtash va turish qoidalari',
  },
  {
    id: 'pedestrians',
    name: 'Пешеходные переходы',
    nameUz: 'Piyodalar o\'tish joyi',
    icon: '🚶',
    description: 'Проезд пешеходных переходов',
    descriptionUz: 'Piyodalar o\'tish joyidan o\'tish',
  },
  {
    id: 'highway',
    name: 'Автомагистрали',
    nameUz: 'Avtomagistrallar',
    icon: '🛤️',
    description: 'Движение по автомагистралям',
    descriptionUz: 'Avtomagistrallarda harakatlanish',
  },
  {
    id: 'passengers',
    name: 'Перевозка пассажиров',
    nameUz: 'Yo\'lovchilarni tashish',
    icon: '👥',
    description: 'Правила перевозки пассажиров и грузов',
    descriptionUz: 'Yo\'lovchi va yuklarni tashish qoidalari',
  },
  {
    id: 'first-aid',
    name: 'Первая помощь',
    nameUz: 'Birinchi yordam',
    icon: '🏥',
    description: 'Оказание первой медицинской помощи',
    descriptionUz: 'Birinchi tibbiy yordam ko\'rsatish',
  },
  {
    id: 'responsibility',
    name: 'Ответственность',
    nameUz: 'Javobgarlik',
    icon: '⚖️',
    description: 'Ответственность водителя за нарушения',
    descriptionUz: 'Haydovchining qoidabuzarlik uchun javobgarligi',
  },
];

export const questions: BaseQuestion[] = [
  // Скоростной режим
  {
    id: 'speed-1',
    topicId: 'speed',
    question: 'Какая максимальная разрешённая скорость движения в населённых пунктах?',
    questionUz: 'Aholi punktlarida ruxsat etilgan maksimal tezlik qancha?',
    options: ['40 км/ч', '50 км/ч', '60 км/ч', '70 км/ч'],
    optionsUz: ['40 km/soat', '50 km/soat', '60 km/soat', '70 km/soat'],
    correctIndex: 2,
    explanation: 'В населённых пунктах максимальная разрешённая скорость составляет 60 км/ч, если иное не указано знаками.',
    explanationUz: 'Aholi punktlarida maksimal ruxsat etilgan tezlik 60 km/soat, agar belgilar boshqasini ko\'rsatmasa.',
  },
  {
    id: 'speed-2',
    topicId: 'speed',
    question: 'Вы въезжаете в город и видите знак начала населённого пункта. До какой скорости нужно снизить движение?',
    questionUz: 'Siz shaharga kirayapsiz va aholi punkti boshlanishi belgisini ko\'rayapsiz. Qanday tezlikkacha sekinlashtirish kerak?',
    options: ['50 км/ч', '60 км/ч', '70 км/ч', '80 км/ч'],
    optionsUz: ['50 km/soat', '60 km/soat', '70 km/soat', '80 km/soat'],
    correctIndex: 1,
    explanation: 'При въезде в населённый пункт необходимо снизить скорость до 60 км/ч.',
    explanationUz: 'Aholi punktiga kirganda tezlikni 60 km/soatgacha kamaytirish kerak.',
  },
  {
    id: 'speed-3',
    topicId: 'speed',
    question: 'Какая максимальная скорость разрешена на автомагистралях Узбекистана?',
    questionUz: 'O\'zbekiston avtomagistrallarida maksimal ruxsat etilgan tezlik qancha?',
    options: ['90 км/ч', '100 км/ч', '110 км/ч', '120 км/ч'],
    optionsUz: ['90 km/soat', '100 km/soat', '110 km/soat', '120 km/soat'],
    correctIndex: 2,
    explanation: 'На автомагистралях Узбекистана максимальная разрешённая скорость составляет 110 км/ч.',
    explanationUz: 'O\'zbekiston avtomagistrallarida maksimal ruxsat etilgan tezlik 110 km/soat.',
  },
  {
    id: 'speed-4',
    topicId: 'speed',
    question: 'Можно ли двигаться со скоростью 70 км/ч в населённом пункте?',
    questionUz: 'Aholi punktida 70 km/soat tezlikda harakatlanish mumkinmi?',
    options: ['Да, всегда можно', 'Нет, это запрещено', 'Только ночью', 'Только на главной дороге'],
    optionsUz: ['Ha, har doim mumkin', 'Yo\'q, bu taqiqlangan', 'Faqat kechasi', 'Faqat asosiy yo\'lda'],
    correctIndex: 1,
    explanation: 'В населённых пунктах скорость ограничена 60 км/ч. Превышение этого лимита является нарушением ПДД.',
    explanationUz: 'Aholi punktlarida tezlik 60 km/soat bilan cheklangan. Bu limitdan oshish YHQ buzilishi hisoblanadi.',
  },
  {
    id: 'speed-5',
    topicId: 'speed',
    question: 'Какая максимальная скорость движения в жилых зонах?',
    questionUz: 'Turar-joy hududlarida maksimal tezlik qancha?',
    options: ['10 км/ч', '20 км/ч', '30 км/ч', '40 км/ч'],
    optionsUz: ['10 km/soat', '20 km/soat', '30 km/soat', '40 km/soat'],
    correctIndex: 1,
    explanation: 'В жилых зонах максимальная разрешённая скорость составляет 20 км/ч для обеспечения безопасности пешеходов.',
    explanationUz: 'Turar-joy hududlarida piyodalar xavfsizligini ta\'minlash uchun maksimal ruxsat etilgan tezlik 20 km/soat.',
  },
  {
    id: 'speed-6',
    topicId: 'speed',
    question: 'Какая максимальная скорость вне населённых пунктов для легковых автомобилей?',
    questionUz: 'Aholi punktlaridan tashqarida yengil avtomobillar uchun maksimal tezlik qancha?',
    options: ['80 км/ч', '90 км/ч', '100 км/ч', '110 км/ч'],
    optionsUz: ['80 km/soat', '90 km/soat', '100 km/soat', '110 km/soat'],
    correctIndex: 2,
    explanation: 'Вне населённых пунктов для легковых автомобилей максимальная скорость составляет 100 км/ч.',
    explanationUz: 'Aholi punktlaridan tashqarida yengil avtomobillar uchun maksimal tezlik 100 km/soat.',
  },

  // Предупреждающие знаки
  {
    id: 'signs-warning-1',
    topicId: 'signs-warning',
    question: 'За сколько метров до опасного участка устанавливаются предупреждающие знаки вне населённых пунктов?',
    questionUz: 'Aholi punktlaridan tashqarida ogohlantiruvchi belgilar xavfli joydan qancha metr oldin o\'rnatiladi?',
    options: ['50-100 м', '100-150 м', '150-300 м', '300-500 м'],
    optionsUz: ['50-100 m', '100-150 m', '150-300 m', '300-500 m'],
    correctIndex: 2,
    explanation: 'Вне населённых пунктов предупреждающие знаки устанавливаются за 150-300 метров до опасного участка.',
    explanationUz: 'Aholi punktlaridan tashqarida ogohlantiruvchi belgilar xavfli joydan 150-300 metr oldin o\'rnatiladi.',
  },
  {
    id: 'signs-warning-2',
    topicId: 'signs-warning',
    question: 'За сколько метров до опасного участка устанавливаются предупреждающие знаки в населённых пунктах?',
    questionUz: 'Aholi punktlarida ogohlantiruvchi belgilar xavfli joydan qancha metr oldin o\'rnatiladi?',
    options: ['30-50 м', '50-100 м', '100-150 м', '150-200 м'],
    optionsUz: ['30-50 m', '50-100 m', '100-150 m', '150-200 m'],
    correctIndex: 1,
    explanation: 'В населённых пунктах предупреждающие знаки устанавливаются за 50-100 метров до опасного участка.',
    explanationUz: 'Aholi punktlarida ogohlantiruvchi belgilar xavfli joydan 50-100 metr oldin o\'rnatiladi.',
  },
  {
    id: 'signs-warning-3',
    topicId: 'signs-warning',
    question: 'Какую форму имеют предупреждающие знаки?',
    questionUz: 'Ogohlantiruvchi belgilar qanday shaklga ega?',
    options: ['Круглую', 'Квадратную', 'Треугольную', 'Прямоугольную'],
    optionsUz: ['Dumaloq', 'Kvadrat', 'Uchburchak', 'To\'g\'ri burchakli'],
    correctIndex: 2,
    explanation: 'Предупреждающие знаки имеют треугольную форму с вершиной вверх и красной окантовкой.',
    explanationUz: 'Ogohlantiruvchi belgilar uchi yuqoriga qaragan uchburchak shaklida va qizil chegarali.',
  },

  // Запрещающие знаки
  {
    id: 'signs-prohibition-1',
    topicId: 'signs-prohibition',
    question: 'Что требует знак "Стоп" (Движение без остановки запрещено)?',
    questionUz: '"To\'xta" belgisi nima talab qiladi?',
    options: ['Снизить скорость', 'Полную остановку', 'Уступить дорогу', 'Включить поворотник'],
    optionsUz: ['Tezlikni kamaytirish', 'To\'liq to\'xtash', 'Yo\'l berish', 'Burilish chiroqini yoqish'],
    correctIndex: 1,
    explanation: 'Знак "Стоп" требует полной остановки транспортного средства перед стоп-линией или краем проезжей части.',
    explanationUz: '"To\'xta" belgisi transport vositasini to\'xta-chizig\'i yoki yo\'l chetida to\'liq to\'xtatishni talab qiladi.',
  },
  {
    id: 'signs-prohibition-2',
    topicId: 'signs-prohibition',
    question: 'Какую форму имеют запрещающие знаки?',
    questionUz: 'Taqiqlovchi belgilar qanday shaklga ega?',
    options: ['Треугольную', 'Квадратную', 'Круглую', 'Прямоугольную'],
    optionsUz: ['Uchburchak', 'Kvadrat', 'Dumaloq', 'To\'g\'ri burchakli'],
    correctIndex: 2,
    explanation: 'Запрещающие знаки имеют круглую форму с красной окантовкой на белом фоне.',
    explanationUz: 'Taqiqlovchi belgilar oq fonda qizil chegarali dumaloq shaklga ega.',
  },

  // Предписывающие знаки
  {
    id: 'signs-mandatory-1',
    topicId: 'signs-mandatory',
    question: 'Какого цвета предписывающие знаки?',
    questionUz: 'Buyruq belgilari qanday rangda?',
    options: ['Красного', 'Белого', 'Синего', 'Зелёного'],
    optionsUz: ['Qizil', 'Oq', 'Ko\'k', 'Yashil'],
    correctIndex: 2,
    explanation: 'Предписывающие знаки имеют синий фон с белыми символами.',
    explanationUz: 'Buyruq belgilari ko\'k fon va oq belgilardan iborat.',
  },

  // Сигналы светофора
  {
    id: 'traffic-lights-1',
    topicId: 'traffic-lights',
    question: 'Что означает жёлтый мигающий сигнал светофора?',
    questionUz: 'Svetoforning sariq miltillovchi signali nima degani?',
    options: ['Остановиться', 'Приготовиться к движению', 'Перекрёсток нерегулируемый', 'Уступить дорогу пешеходам'],
    optionsUz: ['To\'xtash', 'Harakatga tayyorlanish', 'Choraha tartibga solinmagan', 'Piyodalarga yo\'l berish'],
    correctIndex: 2,
    explanation: 'Жёлтый мигающий сигнал означает, что перекрёсток является нерегулируемым и действуют знаки приоритета.',
    explanationUz: 'Sariq miltillovchi signal choraha tartibga solinmaganligini va ustuvorlik belgilari amal qilishini bildiradi.',
  },
  {
    id: 'traffic-lights-2',
    topicId: 'traffic-lights',
    question: 'Можно ли ехать на красный сигнал светофора?',
    questionUz: 'Svetoforning qizil signalida harakatlanish mumkinmi?',
    options: ['Да, если нет машин', 'Да, если очень торопишься', 'Нет, это строго запрещено', 'Да, ночью можно'],
    optionsUz: ['Ha, agar mashina bo\'lmasa', 'Ha, agar juda shoshilsangiz', 'Yo\'q, bu qat\'iyan taqiqlangan', 'Ha, kechasi mumkin'],
    correctIndex: 2,
    explanation: 'Проезд на красный сигнал светофора строго запрещён и является грубым нарушением ПДД.',
    explanationUz: 'Svetoforning qizil signalida o\'tish qat\'iyan taqiqlangan va YHQning og\'ir buzilishi hisoblanadi.',
  },

  // Проезд перекрёстков
  {
    id: 'intersections-1',
    topicId: 'intersections',
    question: 'Кто имеет преимущество на нерегулируемом равнозначном перекрёстке?',
    questionUz: 'Tartibga solinmagan teng ahamiyatli chorahada kim ustunlikka ega?',
    options: ['Транспорт слева', 'Транспорт справа', 'Кто первый подъехал', 'Более крупное транспортное средство'],
    optionsUz: ['Chapdan kelgan transport', 'O\'ngdan kelgan transport', 'Kim avval kelsa', 'Kattaroq transport vositasi'],
    correctIndex: 1,
    explanation: 'На нерегулируемом равнозначном перекрёстке действует правило "помеха справа" - уступаем транспорту справа.',
    explanationUz: 'Tartibga solinmagan teng ahamiyatli chorahada "o\'ngdan to\'siq" qoidasi amal qiladi - o\'ngdan kelgan transportga yo\'l beramiz.',
  },
  {
    id: 'intersections-2',
    topicId: 'intersections',
    question: 'Кто первым проезжает регулируемый перекрёсток?',
    questionUz: 'Tartibga solingan chorahadan kim birinchi o\'tadi?',
    options: ['Автобусы', 'Кому горит зелёный', 'Кто справа', 'Спецтранспорт'],
    optionsUz: ['Avtobuslar', 'Kimga yashil yonsa', 'O\'ngdan kelgan', 'Maxsus transport'],
    correctIndex: 1,
    explanation: 'На регулируемом перекрёстке движение осуществляется по сигналам светофора или регулировщика.',
    explanationUz: 'Tartibga solingan chorahada harakat svetofor yoki tartibga soluvchi signallari bo\'yicha amalga oshiriladi.',
  },

  // Обгон
  {
    id: 'overtaking-1',
    topicId: 'overtaking',
    question: 'Где запрещён обгон?',
    questionUz: 'Quvib o\'tish qayerda taqiqlangan?',
    options: ['На прямой дороге', 'На пешеходных переходах', 'За городом', 'При хорошей видимости'],
    optionsUz: ['To\'g\'ri yo\'lda', 'Piyodalar o\'tish joylarida', 'Shahar tashqarisida', 'Yaxshi ko\'rinishda'],
    correctIndex: 1,
    explanation: 'Обгон запрещён на пешеходных переходах, перекрёстках, железнодорожных переездах и в других опасных местах.',
    explanationUz: 'Quvib o\'tish piyodalar o\'tish joylarida, chorahalarda, temir yo\'l o\'tish joylarida va boshqa xavfli joylarda taqiqlangan.',
  },
  {
    id: 'overtaking-2',
    topicId: 'overtaking',
    question: 'С какой стороны разрешён обгон?',
    questionUz: 'Qaysi tomondan quvib o\'tishga ruxsat beriladi?',
    options: ['Справа', 'Слева', 'С любой стороны', 'По обочине'],
    optionsUz: ['O\'ngdan', 'Chapdan', 'Har qanday tomondan', 'Yo\'l chetidan'],
    correctIndex: 1,
    explanation: 'Обгон транспортных средств производится только слева. Обгон справа запрещён.',
    explanationUz: 'Transport vositalarini quvib o\'tish faqat chapdan amalga oshiriladi. O\'ngdan quvib o\'tish taqiqlangan.',
  },

  // Остановка и стоянка
  {
    id: 'parking-1',
    topicId: 'parking',
    question: 'На каком расстоянии от пешеходного перехода запрещена остановка?',
    questionUz: 'Piyodalar o\'tish joyidan qancha masofada to\'xtash taqiqlanadi?',
    options: ['3 метра', '5 метров', '10 метров', '15 метров'],
    optionsUz: ['3 metr', '5 metr', '10 metr', '15 metr'],
    correctIndex: 1,
    explanation: 'Остановка запрещена ближе 5 метров от пешеходного перехода.',
    explanationUz: 'Piyodalar o\'tish joyidan 5 metrdan yaqin joyda to\'xtash taqiqlangan.',
  },
  {
    id: 'parking-2',
    topicId: 'parking',
    question: 'На каком расстоянии от остановки общественного транспорта запрещена остановка?',
    questionUz: 'Jamoat transporti bekatidan qancha masofada to\'xtash taqiqlanadi?',
    options: ['10 метров', '15 метров', '20 метров', '25 метров'],
    optionsUz: ['10 metr', '15 metr', '20 metr', '25 metr'],
    correctIndex: 1,
    explanation: 'Остановка запрещена ближе 15 метров от остановки маршрутных транспортных средств.',
    explanationUz: 'Yo\'nalish bo\'ylab harakatlanuvchi transport bekatidan 15 metrdan yaqin joyda to\'xtash taqiqlangan.',
  },

  // Пешеходные переходы
  {
    id: 'pedestrians-1',
    topicId: 'pedestrians',
    question: 'Обязан ли водитель пропустить пешехода на нерегулируемом переходе?',
    questionUz: 'Haydovchi tartibga solinmagan o\'tish joyida piyodani o\'tkazib yuborishi shartmi?',
    options: ['Только если пешеход на проезжей части', 'Да, всегда', 'Нет, пешеход должен ждать', 'Только днём'],
    optionsUz: ['Faqat piyoda yo\'l qismida bo\'lsa', 'Ha, har doim', 'Yo\'q, piyoda kutishi kerak', 'Faqat kunduz'],
    correctIndex: 1,
    explanation: 'Водитель обязан уступить дорогу пешеходам, переходящим проезжую часть по нерегулируемому переходу.',
    explanationUz: 'Haydovchi tartibga solinmagan o\'tish joyi orqali yo\'lni kesib o\'tayotgan piyodalarga yo\'l berishi shart.',
  },

  // Автомагистрали
  {
    id: 'highway-1',
    topicId: 'highway',
    question: 'Какая минимальная скорость движения на автомагистрали?',
    questionUz: 'Avtomagistralda minimal tezlik qancha?',
    options: ['30 км/ч', '40 км/ч', '50 км/ч', '60 км/ч'],
    optionsUz: ['30 km/soat', '40 km/soat', '50 km/soat', '60 km/soat'],
    correctIndex: 1,
    explanation: 'На автомагистрали запрещено движение транспортных средств, скорость которых по технической характеристике менее 40 км/ч.',
    explanationUz: 'Avtomagistralda texnik xususiyatiga ko\'ra tezligi 40 km/soatdan kam bo\'lgan transport vositalarining harakati taqiqlangan.',
  },
  {
    id: 'highway-2',
    topicId: 'highway',
    question: 'Разрешён ли разворот на автомагистрали?',
    questionUz: 'Avtomagistralda burilish mumkinmi?',
    options: ['Да, в любом месте', 'Да, через разрывы разделительной полосы', 'Нет, запрещён', 'Да, на развязках'],
    optionsUz: ['Ha, istalgan joyda', 'Ha, ajratuvchi chiziq oraliqlarida', 'Yo\'q, taqiqlangan', 'Ha, aylanma yo\'llarda'],
    correctIndex: 2,
    explanation: 'Разворот и въезд в технологические разрывы разделительной полосы на автомагистрали запрещён.',
    explanationUz: 'Avtomagistralda burilish va ajratuvchi chiziqning texnologik oraliqlariga kirish taqiqlangan.',
  },

  // Перевозка пассажиров
  {
    id: 'passengers-1',
    topicId: 'passengers',
    question: 'С какого возраста разрешена перевозка детей на переднем сиденье?',
    questionUz: 'Necha yoshdan bolalarni old o\'rindiqda tashish mumkin?',
    options: ['С 10 лет', 'С 12 лет', 'С 14 лет', 'С 16 лет'],
    optionsUz: ['10 yoshdan', '12 yoshdan', '14 yoshdan', '16 yoshdan'],
    correctIndex: 1,
    explanation: 'Перевозка детей до 12 лет на переднем сиденье без специального удерживающего устройства запрещена.',
    explanationUz: '12 yoshgacha bolalarni maxsus ushlab turuvchi qurilmasiz old o\'rindiqda tashish taqiqlangan.',
  },

  // Первая помощь
  {
    id: 'first-aid-1',
    topicId: 'first-aid',
    question: 'Где накладывается жгут при артериальном кровотечении?',
    questionUz: 'Arterial qon ketishida jgut qayerga qo\'yiladi?',
    options: ['Ниже раны', 'Выше раны', 'На саму рану', 'На противоположную конечность'],
    optionsUz: ['Yaradan pastroqda', 'Yaradan yuqorida', 'Yaraning o\'ziga', 'Qarama-qarshi oyoq/qo\'lga'],
    correctIndex: 1,
    explanation: 'При артериальном кровотечении жгут накладывается выше раны для остановки притока крови.',
    explanationUz: 'Arterial qon ketishida qon oqimini to\'xtatish uchun jgut yaradan yuqoriga qo\'yiladi.',
  },
  {
    id: 'first-aid-2',
    topicId: 'first-aid',
    question: 'Какое соотношение нажатий и вдохов при проведении сердечно-лёгочной реанимации?',
    questionUz: 'Yurak-o\'pka reanimatsiyasida bosish va nafas olish nisbati qanday?',
    options: ['15 нажатий, 2 вдоха', '30 нажатий, 2 вдоха', '20 нажатий, 1 вдох', '10 нажатий, 3 вдоха'],
    optionsUz: ['15 bosish, 2 nafas', '30 bosish, 2 nafas', '20 bosish, 1 nafas', '10 bosish, 3 nafas'],
    correctIndex: 1,
    explanation: 'При проведении сердечно-лёгочной реанимации соотношение составляет 30 нажатий на грудную клетку и 2 вдоха.',
    explanationUz: 'Yurak-o\'pka reanimatsiyasida nisbat 30 marta ko\'krakka bosish va 2 nafas.',
  },
  {
    id: 'first-aid-3',
    topicId: 'first-aid',
    question: 'Что нужно сделать при переломе конечности?',
    questionUz: 'Oyoq-qo\'l singanida nima qilish kerak?',
    options: ['Вправить кость', 'Наложить шину (иммобилизация)', 'Растереть место перелома', 'Согреть конечность'],
    optionsUz: ['Suyakni joyiga qo\'yish', 'Shina qo\'yish (immobilizatsiya)', 'Singan joyni ishqalash', 'Oyoq-qo\'lni isitish'],
    correctIndex: 1,
    explanation: 'При переломе необходимо обеспечить неподвижность (иммобилизацию) повреждённой конечности с помощью шины.',
    explanationUz: 'Sinishda shina yordamida shikastlangan oyoq-qo\'lni harakatsiz holda (immobilizatsiya) ta\'minlash kerak.',
  },

  // Ответственность
  {
    id: 'responsibility-1',
    topicId: 'responsibility',
    question: 'Какое наказание предусмотрено за управление ТС в нетрезвом состоянии?',
    questionUz: 'Mast holatda transport vositasini boshqarganlik uchun qanday jazo nazarda tutilgan?',
    options: ['Предупреждение', 'Штраф', 'Лишение прав и штраф', 'Только штраф'],
    optionsUz: ['Ogohlantirish', 'Jarima', 'Huquqdan mahrum qilish va jarima', 'Faqat jarima'],
    correctIndex: 2,
    explanation: 'За управление транспортным средством в нетрезвом состоянии предусмотрено лишение водительских прав и крупный штраф.',
    explanationUz: 'Mast holatda transport vositasini boshqarganlik uchun haydovchilik huquqidan mahrum qilish va katta jarima nazarda tutilgan.',
  },

  // Разметка
  {
    id: 'marking-1',
    topicId: 'marking',
    question: 'Что означает сплошная линия разметки?',
    questionUz: 'Uzluksiz chiziq belgisi nima degani?',
    options: ['Можно пересекать', 'Запрещено пересекать', 'Рекомендуется не пересекать', 'Можно пересекать ночью'],
    optionsUz: ['Kesib o\'tish mumkin', 'Kesib o\'tish taqiqlangan', 'Kesib o\'tmaslik tavsiya etiladi', 'Kechasi kesib o\'tish mumkin'],
    correctIndex: 1,
    explanation: 'Сплошную линию разметки пересекать запрещено.',
    explanationUz: 'Uzluksiz chiziqni kesib o\'tish taqiqlangan.',
  },
  {
    id: 'marking-2',
    topicId: 'marking',
    question: 'Что означает прерывистая линия разметки?',
    questionUz: 'Uzilgan chiziq belgisi nima degani?',
    options: ['Запрещено пересекать', 'Разрешено пересекать', 'Пешеходный переход', 'Стоянка запрещена'],
    optionsUz: ['Kesib o\'tish taqiqlangan', 'Kesib o\'tish ruxsat', 'Piyodalar o\'tish joyi', 'Turish taqiqlangan'],
    correctIndex: 1,
    explanation: 'Прерывистую линию разметки можно пересекать при перестроении и обгоне.',
    explanationUz: 'Uzilgan chiziqni qayta joylashish va quvib o\'tishda kesib o\'tish mumkin.',
  },
];

export const defaultSettings = {
  language: 'ru' as const,
  timerEnabled: false,
  questionsPerSession: 20,
  soundEnabled: true,
  theme: 'light' as const,
};
