import { Topic, BaseQuestion, Settings } from './types';

export const defaultSettings: Settings = {
  language: 'ru',
  timerEnabled: true,
  questionsPerSession: 20,
  soundEnabled: true,
  theme: 'light',
};

export const topics: Topic[] = [
  {
    id: 'speed',
    name: 'Скоростной режим',
    nameUz: 'Tezlik rejimi',
    icon: 'Gauge',
    description: 'Ограничения скорости на различных дорогах',
    descriptionUz: 'Turli yo\'llarda tezlik cheklovlari',
  },
  {
    id: 'signs-warning',
    name: 'Предупреждающие знаки',
    nameUz: 'Ogohlantiruvchi belgilar',
    icon: 'AlertTriangle',
    description: 'Знаки, предупреждающие об опасности',
    descriptionUz: 'Xavf haqida ogohlantiradigan belgilar',
  },
  {
    id: 'signs-prohibition',
    name: 'Запрещающие знаки',
    nameUz: 'Taqiqlovchi belgilar',
    icon: 'Ban',
    description: 'Знаки, запрещающие определённые действия',
    descriptionUz: 'Ma\'lum harakatlarni taqiqlaydigan belgilar',
  },
  {
    id: 'signs-mandatory',
    name: 'Предписывающие знаки',
    nameUz: 'Buyruq belgilari',
    icon: 'ArrowRight',
    description: 'Знаки, указывающие обязательные направления',
    descriptionUz: 'Majburiy yo\'nalishlarni ko\'rsatadigan belgilar',
  },
  {
    id: 'signs-info',
    name: 'Информационные знаки',
    nameUz: 'Axborot belgilari',
    icon: 'Info',
    description: 'Знаки, информирующие водителя',
    descriptionUz: 'Haydovchini xabardor qiluvchi belgilar',
  },
  {
    id: 'marking',
    name: 'Дорожная разметка',
    nameUz: 'Yo\'l chiziqlari',
    icon: 'Route',
    description: 'Горизонтальная и вертикальная разметка',
    descriptionUz: 'Gorizontal va vertikal chiziqlar',
  },
  {
    id: 'traffic-lights',
    name: 'Сигналы светофора',
    nameUz: 'Svetofor signallari',
    icon: 'CircleDot',
    description: 'Значение сигналов светофора и регулировщика',
    descriptionUz: 'Svetofor va tartibga soluvchi signallari ma\'nosi',
  },
  {
    id: 'intersections',
    name: 'Проезд перекрёстков',
    nameUz: 'Chorrahalardan o\'tish',
    icon: 'GitMerge',
    description: 'Правила проезда различных перекрёстков',
    descriptionUz: 'Turli chorrahalardan o\'tish qoidalari',
  },
  {
    id: 'overtaking',
    name: 'Обгон и опережение',
    nameUz: 'Quvib o\'tish',
    icon: 'ArrowLeftRight',
    description: 'Правила выполнения обгона',
    descriptionUz: 'Quvib o\'tish qoidalari',
  },
  {
    id: 'parking',
    name: 'Остановка и стоянка',
    nameUz: 'To\'xtash va turish',
    icon: 'ParkingCircle',
    description: 'Правила остановки и стоянки',
    descriptionUz: 'To\'xtash va turish qoidalari',
  },
  {
    id: 'pedestrians',
    name: 'Пешеходные переходы',
    nameUz: 'Piyodalar o\'tish joyi',
    icon: 'Footprints',
    description: 'Проезд пешеходных переходов',
    descriptionUz: 'Piyodalar o\'tish joyidan o\'tish',
  },
  {
    id: 'highway',
    name: 'Автомагистрали',
    nameUz: 'Avtomagistrallar',
    icon: 'Milestone',
    description: 'Движение по автомагистралям',
    descriptionUz: 'Avtomagistrallarda harakatlanish',
  },
  {
    id: 'passengers',
    name: 'Перевозка пассажиров',
    nameUz: 'Yo\'lovchilarni tashish',
    icon: 'Users',
    description: 'Правила перевозки пассажиров и грузов',
    descriptionUz: 'Yo\'lovchi va yuklarni tashish qoidalari',
  },
  {
    id: 'first-aid',
    name: 'Первая помощь',
    nameUz: 'Birinchi yordam',
    icon: 'Heart',
    description: 'Оказание первой медицинской помощи',
    descriptionUz: 'Birinchi tibbiy yordam ko\'rsatish',
  },
  {
    id: 'responsibility',
    name: 'Ответственность',
    nameUz: 'Javobgarlik',
    icon: 'Scale',
    description: 'Ответственность водителя за нарушения',
    descriptionUz: 'Haydovchining qoidabuzarlik uchun javobgarligi',
  },
];

export const questions: BaseQuestion[] = [
  // Скоростной режим
  {
    id: 'speed-1',
    topicId: 'speed',
    question: 'Какая максимальная разрешённая скорость движения в населённых пунктах?',
    questionUz: 'Aholi punktlarida ruxsat etilgan maksimal tezlik qancha?',
    options: ['40 км/ч', '50 км/ч', '60 км/ч', '70 км/ч'],
    optionsUz: ['40 km/soat', '50 km/soat', '60 km/soat', '70 km/soat'],
    correctIndex: 2,
    explanation: 'В населённых пунктах максимальная разрешённая скорость составляет 60 км/ч, если иное не указано знаками.',
    explanationUz: 'Aholi punktlarida maksimal ruxsat etilgan tezlik 60 km/soat, agar belgilar boshqasini ko\'rsatmasa.',
  },
  {
    id: 'speed-2',
    topicId: 'speed',
    question: 'Вы въезжаете в город и видите знак начала населённого пункта. До какой скорости нужно снизить движение?',
    questionUz: 'Siz shaharga kirayapsiz va aholi punkti boshlanishi belgisini ko\'rayapsiz. Qanday tezlikkacha sekinlashtirish kerak?',
    options: ['50 км/ч', '60 км/ч', '70 км/ч', '80 км/ч'],
    optionsUz: ['50 km/soat', '60 km/soat', '70 km/soat', '80 km/soat'],
    correctIndex: 1,
    explanation: 'При въезде в населённый пункт необходимо снизить скорость до 60 км/ч.',
    explanationUz: 'Aholi punktiga kirganda tezlikni 60 km/soatgacha kamaytirish kerak.',
  },
  {
    id: 'speed-3',
    topicId: 'speed',
    question: 'Какая максимальная скорость разрешена на автомагистралях Узбекистана?',
    questionUz: 'O\'zbekiston avtomagistrallarida maksimal ruxsat etilgan tezlik qancha?',
    options: ['90 км/ч', '100 км/ч', '110 км/ч', '120 км/ч'],
    optionsUz: ['90 km/soat', '100 km/soat', '110 km/soat', '120 km/soat'],
    correctIndex: 2,
    explanation: 'На автомагистралях Узбекистана максимальная разрешённая скорость составляет 110 км/ч.',
    explanationUz: 'O\'zbekiston avtomagistrallarida maksimal ruxsat etilgan tezlik 110 km/soat.',
  },
  {
    id: 'speed-4',
    topicId: 'speed',
    question: 'Можно ли двигаться со скоростью 70 км/ч в населённом пункте?',
    questionUz: 'Aholi punktida 70 km/soat tezlikda harakatlanish mumkinmi?',
    options: ['Да, всегда можно', 'Нет, это запрещено', 'Только ночью', 'Только на главной дороге'],
    optionsUz: ['Ha, har doim mumkin', 'Yo\'q, bu taqiqlangan', 'Faqat kechasi', 'Faqat asosiy yo\'lda'],
    correctIndex: 1,
    explanation: 'В населённых пунктах скорость ограничена 60 км/ч. Превышение этого лимита является нарушением ПДД.',
    explanationUz: 'Aholi punktlarida tezlik 60 km/soat bilan cheklangan. Bu limitdan oshish YHQ buzilishi hisoblanadi.',
  },
  {
    id: 'speed-5',
    topicId: 'speed',
    question: 'Какая максимальная скорость движения в жилых зонах?',
    questionUz: 'Turar-joy hududlarida maksimal tezlik qancha?',
    options: ['10 км/ч', '20 км/ч', '30 км/ч', '40 км/ч'],
    optionsUz: ['10 km/soat', '20 km/soat', '30 km/soat', '40 km/soat'],
    correctIndex: 1,
    explanation: 'В жилых зонах максимальная разрешённая скорость составляет 20 км/ч для обеспечения безопасности пешеходов.',
    explanationUz: 'Turar-joy hududlarida piyodalar xavfsizligini ta\'minlash uchun maksimal ruxsat etilgan tezlik 20 km/soat.',
  },
  {
    id: 'speed-6',
    topicId: 'speed',
    question: 'Какая максимальная скорость вне населённых пунктов для легковых автомобилей?',
    questionUz: 'Aholi punktlaridan tashqarida yengil avtomobillar uchun maksimal tezlik qancha?',
    options: ['80 км/ч', '90 км/ч', '100 км/ч', '110 км/ч'],
    optionsUz: ['80 km/soat', '90 km/soat', '100 km/soat', '110 km/soat'],
    correctIndex: 2,
    explanation: 'Вне населённых пунктов для легковых автомобилей максимальная скорость составляет 100 км/ч.',
    explanationUz: 'Aholi punktlaridan tashqarida yengil avtomobillar uchun maksimal tezlik 100 km/soat.',
  },

  // Предупреждающие знаки
  {
    id: 'signs-warning-1',
    topicId: 'signs-warning',
    question: 'За сколько метров до опасного участка устанавливаются предупреждающие знаки вне населённых пунктов?',
    questionUz: 'Aholi punktlaridan tashqarida ogohlantiruvchi belgilar xavfli joydan qancha metr oldin o\'rnatiladi?',
    options: ['50-100 м', '100-150 м', '150-300 м', '300-500 м'],
    optionsUz: ['50-100 m', '100-150 m', '150-300 m', '300-500 m'],
    correctIndex: 2,
    explanation: 'Вне населённых пунктов предупреждающие знаки устанавливаются за 150-300 метров до опасного участка.',
    explanationUz: 'Aholi punktlaridan tashqarida ogohlantiruvchi belgilar xavfli joydan 150-300 metr oldin o\'rnatiladi.',
  },
  {
    id: 'signs-warning-2',
    topicId: 'signs-warning',
    question: 'За сколько метров до опасного участка устанавливаются предупреждающие знаки в населённых пунктах?',
    questionUz: 'Aholi punktlarida ogohlantiruvchi belgilar xavfli joydan qancha metr oldin o\'rnatiladi?',
    options: ['30-50 м', '50-100 м', '100-150 м', '150-200 м'],
    optionsUz: ['30-50 m', '50-100 m', '100-150 m', '150-200 m'],
    correctIndex: 1,
    explanation: 'В населённых пунктах предупреждающие знаки устанавливаются за 50-100 метров до опасного участка.',
    explanationUz: 'Aholi punktlarida ogohlantiruvchi belgilar xavfli joydan 50-100 metr oldin o\'rnatiladi.',
  },
  {
    id: 'signs-warning-3',
    topicId: 'signs-warning',
    question: 'Какую форму имеют предупреждающие знаки?',
    questionUz: 'Ogohlantiruvchi belgilar qanday shaklga ega?',
    options: ['Круглую', 'Квадратную', 'Треугольную', 'Прямоугольную'],
    optionsUz: ['Dumaloq', 'Kvadrat', 'Uchburchak', 'To\'g\'ri burchakli'],
    correctIndex: 2,
    explanation: 'Предупреждающие знаки имеют треугольную форму с вершиной вверх и красной окантовкой.',
    explanationUz: 'Ogohlantiruvchi belgilar uchi yuqoriga qaragan uchburchak shaklida va qizil chegarali.',
  },

  // Запрещающие знаки
  {
    id: 'signs-prohibition-1',
    topicId: 'signs-prohibition',
    question: 'Что требует знак "Стоп" (Движение без остановки запрещено)?',
    questionUz: '"To\'xta" belgisi nima talab qiladi?',
    options: ['Снизить скорость', 'Полную остановку', 'Уступить дорогу', 'Включить поворотник'],
    optionsUz: ['Tezlikni kamaytirish', 'To\'liq to\'xtash', 'Yo\'l berish', 'Burilish chiroqini yoqish'],
    correctIndex: 1,
    explanation: 'Знак "Стоп" требует полной остановки транспортного средства перед стоп-линией или краем проезжей части.',
    explanationUz: '"To\'xta" belgisi transport vositasini to\'xta-chizig\'i yoki yo\'l chetida to\'liq to\'xtatishni talab qiladi.',
  },
  {
    id: 'signs-prohibition-2',
    topicId: 'signs-prohibition',
    question: 'Какую форму имеют запрещающие знаки?',
    questionUz: 'Taqiqlovchi belgilar qanday shaklga ega?',
    options: ['Треугольную', 'Квадратную', 'Круглую', 'Прямоугольную'],
    optionsUz: ['Uchburchak', 'Kvadrat', 'Dumaloq', 'To\'g\'ri burchakli'],
    correctIndex: 2,
    explanation: 'Запрещающие знаки имеют круглую форму с красной окантовкой на белом фоне.',
    explanationUz: 'Taqiqlovchi belgilar oq fonda qizil chegarali dumaloq shaklga ega.',
  },

  // Предписывающие знаки
  {
    id: 'signs-mandatory-1',
    topicId: 'signs-mandatory',
    question: 'Какого цвета предписывающие знаки?',
    questionUz: 'Buyruq belgilari qanday rangda?',
    options: ['Красного', 'Белого', 'Синего', 'Зелёного'],
    optionsUz: ['Qizil', 'Oq', 'Ko\'k', 'Yashil'],
    correctIndex: 2,
    explanation: 'Предписывающие знаки имеют синий фон с белыми символами.',
    explanationUz: 'Buyruq belgilari ko\'k fon va oq belgilardan iborat.',
  },

  // Сигналы светофора
  {
    id: 'traffic-lights-1',
    topicId: 'traffic-lights',
    question: 'Что означает жёлтый мигающий сигнал светофора?',
    questionUz: 'Svetoforning sariq miltillovchi signali nima degani?',
    options: ['Остановиться', 'Приготовиться к движению', 'Перекрёсток нерегулируемый', 'Уступить дорогу пешеходам'],
    optionsUz: ['To\'xtash', 'Harakatga tayyorlanish', 'Choraha tartibga solinmagan', 'Piyodalarga yo\'l berish'],
    correctIndex: 2,
    explanation: 'Жёлтый мигающий сигнал означает, что перекрёсток является нерегулируемым и действуют знаки приоритета.',
    explanationUz: 'Sariq miltillovchi signal choraha tartibga solinmaganligini va ustuvorlik belgilari amal qilishini bildiradi.',
  },
  {
    id: 'traffic-lights-2',
    topicId: 'traffic-lights',
    question: 'Можно ли ехать на красный сигнал светофора?',
    questionUz: 'Svetoforning qizil signalida harakatlanish mumkinmi?',
    options: ['Да, если нет машин', 'Да, если очень торопишься', 'Нет, это строго запрещено', 'Да, ночью можно'],
    optionsUz: ['Ha, agar mashina bo\'lmasa', 'Ha, agar juda shoshilsangiz', 'Yo\'q, bu qat\'iyan taqiqlangan', 'Ha, kechasi mumkin'],
    correctIndex: 2,
    explanation: 'Проезд на красный сигнал светофора строго запрещён и является грубым нарушением ПДД.',
    explanationUz: 'Svetoforning qizil signalida o\'tish qat\'iyan taqiqlangan va YHQning og\'ir buzilishi hisoblanadi.',
  },

  // Проезд перекрёстков
  {
    id: 'intersections-1',
    topicId: 'intersections',
    question: 'Кто имеет преимущество на нерегулируемом равнозначном перекрёстке?',
    questionUz: 'Tartibga solinmagan teng ahamiyatli chorahada kim ustunlikka ega?',
    options: ['Транспорт слева', 'Транспорт справа', 'Кто первый подъехал', 'Более крупное транспортное средство'],
    optionsUz: ['Chapdan kelgan transport', 'O\'ngdan kelgan transport', 'Kim avval kelsa', 'Kattaroq transport vositasi'],
    correctIndex: 1,
    explanation: 'На нерегулируемом равнозначном перекрёстке действует правило "помеха справа" - уступаем транспорту справа.',
    explanationUz: 'Tartibga solinmagan teng ahamiyatli chorahada "o\'ngdan to\'siq" qoidasi amal qiladi - o\'ngdan kelgan transportga yo\'l beramiz.',
  },
  {
    id: 'intersections-2',
    topicId: 'intersections',
    question: 'Кто первым проезжает регулируемый перекрёсток?',
    questionUz: 'Tartibga solingan chorahadan kim birinchi o\'tadi?',
    options: ['Автобусы', 'Кому горит зелёный', 'Кто справа', 'Спецтранспорт'],
    optionsUz: ['Avtobuslar', 'Kimga yashil yonsa', 'O\'ngdan kelgan', 'Maxsus transport'],
    correctIndex: 1,
    explanation: 'На регулируемом перекрёстке движение осуществляется по сигналам светофора или регулировщика.',
    explanationUz: 'Tartibga solingan chorahada harakat svetofor yoki tartibga soluvchi signallari bo\'yicha amalga oshiriladi.',
  },

  // Обгон
  {
    id: 'overtaking-1',
    topicId: 'overtaking',
    question: 'Где запрещён обгон?',
    questionUz: 'Quvib o\'tish qayerda taqiqlangan?',
    options: ['На прямой дороге', 'На пешеходных переходах', 'За городом', 'При хорошей видимости'],
    optionsUz: ['To\'g\'ri yo\'lda', 'Piyodalar o\'tish joylarida', 'Shahar tashqarisida', 'Yaxshi ko\'rinishda'],
    correctIndex: 1,
    explanation: 'Обгон запрещён на пешеходных переходах, перекрёстках, железнодорожных переездах и в других опасных местах.',
    explanationUz: 'Quvib o\'tish piyodalar o\'tish joylarida, chorahalarda, temir yo\'l o\'tish joylarida va boshqa xavfli joylarda taqiqlangan.',
  },
  {
    id: 'overtaking-2',
    topicId: 'overtaking',
    question: 'Можно ли обгонять на подъёме?',
    questionUz: 'Qiyalikda quvib o\'tish mumkinmi?',
    options: ['Да, всегда', 'Нет, запрещено', 'Только грузовики', 'Только мотоциклы'],
    optionsUz: ['Ha, har doim', 'Yo\'q, taqiqlangan', 'Faqat yuk mashinalari', 'Faqat mototsikllar'],
    correctIndex: 1,
    explanation: 'Обгон запрещён в конце подъёма и на других участках дорог с ограниченной видимостью.',
    explanationUz: 'Quvib o\'tish qiyalik oxirida va cheklangan ko\'rinishga ega bo\'lgan boshqa yo\'l qismlarida taqiqlangan.',
  },

  // Стоянка и остановка
  {
    id: 'parking-1',
    topicId: 'parking',
    question: 'На каком расстоянии от пешеходного перехода запрещена остановка?',
    questionUz: 'Piyodalar o\'tish joyidan qancha masofada to\'xtash taqiqlangan?',
    options: ['3 метра', '5 метров', '10 метров', '15 метров'],
    optionsUz: ['3 metr', '5 metr', '10 metr', '15 metr'],
    correctIndex: 1,
    explanation: 'Остановка запрещена ближе 5 метров перед пешеходным переходом.',
    explanationUz: 'Piyodalar o\'tish joyidan 5 metr oldin to\'xtash taqiqlangan.',
  },
  {
    id: 'parking-2',
    topicId: 'parking',
    question: 'Где запрещена стоянка?',
    questionUz: 'Turish qayerda taqiqlangan?',
    options: ['На тротуаре', 'Ближе 50 м от ж/д переезда', 'На обочине', 'У магазина'],
    optionsUz: ['Piyoda yo\'lagida', 'Temir yo\'l o\'tishdan 50 m yaqin', 'Yo\'l chetida', 'Do\'kon oldida'],
    correctIndex: 1,
    explanation: 'Стоянка запрещена ближе 50 метров от железнодорожного переезда.',
    explanationUz: 'Temir yo\'l o\'tishidan 50 metr yaqin turish taqiqlangan.',
  },

  // Пешеходные переходы
  {
    id: 'pedestrians-1',
    topicId: 'pedestrians',
    question: 'Что должен сделать водитель при приближении к пешеходному переходу?',
    questionUz: 'Haydovchi piyodalar o\'tish joyiga yaqinlashganda nima qilishi kerak?',
    options: ['Посигналить', 'Снизить скорость', 'Включить аварийку', 'Ничего'],
    optionsUz: ['Signal berish', 'Tezlikni kamaytirish', 'Avariya signalini yoqish', 'Hech narsa'],
    correctIndex: 1,
    explanation: 'При приближении к пешеходному переходу водитель должен снизить скорость и быть готовым остановиться.',
    explanationUz: 'Piyodalar o\'tish joyiga yaqinlashganda haydovchi tezlikni kamaytirishi va to\'xtashga tayyor bo\'lishi kerak.',
  },
  {
    id: 'pedestrians-2',
    topicId: 'pedestrians',
    question: 'Можно ли обгонять на пешеходном переходе?',
    questionUz: 'Piyodalar o\'tish joyida quvib o\'tish mumkinmi?',
    options: ['Да, если нет пешеходов', 'Да, но медленно', 'Нет, запрещено', 'Только ночью'],
    optionsUz: ['Ha, agar piyoda bo\'lmasa', 'Ha, lekin sekin', 'Yo\'q, taqiqlangan', 'Faqat kechasi'],
    correctIndex: 2,
    explanation: 'Обгон на пешеходном переходе запрещён в любых условиях.',
    explanationUz: 'Piyodalar o\'tish joyida quvib o\'tish har qanday sharoitda taqiqlangan.',
  },

  // Автомагистрали
  {
    id: 'highway-1',
    topicId: 'highway',
    question: 'Какая минимальная скорость движения на автомагистрали?',
    questionUz: 'Avtomagistralda minimal tezlik qancha?',
    options: ['30 км/ч', '40 км/ч', '50 км/ч', '60 км/ч'],
    optionsUz: ['30 km/soat', '40 km/soat', '50 km/soat', '60 km/soat'],
    correctIndex: 1,
    explanation: 'На автомагистрали запрещено движение со скоростью менее 40 км/ч.',
    explanationUz: 'Avtomagistralda 40 km/soatdan past tezlikda harakatlanish taqiqlangan.',
  },
  {
    id: 'highway-2',
    topicId: 'highway',
    question: 'Можно ли остановиться на автомагистрали?',
    questionUz: 'Avtomagistralda to\'xtash mumkinmi?',
    options: ['Да, в любом месте', 'Только на обочине', 'Только в специальных местах', 'Нет, запрещено везде'],
    optionsUz: ['Ha, istalgan joyda', 'Faqat yo\'l chetida', 'Faqat maxsus joylarda', 'Yo\'q, hamma joyda taqiqlangan'],
    correctIndex: 2,
    explanation: 'На автомагистрали остановка разрешена только в специально отведённых местах.',
    explanationUz: 'Avtomagistralda to\'xtash faqat maxsus ajratilgan joylarda ruxsat etiladi.',
  },

  // Перевозка пассажиров
  {
    id: 'passengers-1',
    topicId: 'passengers',
    question: 'Со скольких лет ребёнок может ездить на переднем сиденье без детского кресла?',
    questionUz: 'Bola necha yoshdan bolalar o\'rindig\'isiz old o\'rindiqda o\'tirishi mumkin?',
    options: ['С 10 лет', 'С 12 лет', 'С 14 лет', 'С 16 лет'],
    optionsUz: ['10 yoshdan', '12 yoshdan', '14 yoshdan', '16 yoshdan'],
    correctIndex: 1,
    explanation: 'Дети до 12 лет должны перевозиться в детских удерживающих устройствах.',
    explanationUz: '12 yoshgacha bolalar bolalar ushlab turuvchi qurilmalarida tashilishi kerak.',
  },
  {
    id: 'passengers-2',
    topicId: 'passengers',
    question: 'Обязательно ли пристёгиваться ремнём безопасности?',
    questionUz: 'Xavfsizlik kamarini taqish majburiymi?',
    options: ['Только водителю', 'Только на трассе', 'Всем, всегда', 'Только в городе'],
    optionsUz: ['Faqat haydovchiga', 'Faqat trassada', 'Hammaga, har doim', 'Faqat shaharda'],
    correctIndex: 2,
    explanation: 'Ремнями безопасности должны пристёгиваться все: водитель и пассажиры на всех сиденьях.',
    explanationUz: 'Xavfsizlik kamarlari bilan barcha: haydovchi va barcha o\'rindiqlardagi yo\'lovchilar bog\'lanishi kerak.',
  },

  // Первая помощь
  {
    id: 'first-aid-1',
    topicId: 'first-aid',
    question: 'Что нужно сделать при артериальном кровотечении?',
    questionUz: 'Arterial qon ketishda nima qilish kerak?',
    options: ['Промыть рану', 'Наложить жгут выше раны', 'Приложить лёд', 'Ничего не делать'],
    optionsUz: ['Yarani yuvish', 'Yaradan yuqoriga jgut qo\'yish', 'Muz qo\'yish', 'Hech narsa qilmaslik'],
    correctIndex: 1,
    explanation: 'При артериальном кровотечении необходимо наложить жгут выше места ранения.',
    explanationUz: 'Arterial qon ketishda yaralangan joydan yuqoriroqqa jgut qo\'yish kerak.',
  },
  {
    id: 'first-aid-2',
    topicId: 'first-aid',
    question: 'Каково соотношение нажатий и вдохов при сердечно-лёгочной реанимации?',
    questionUz: 'Yurak-o\'pka reanimatsiyasida bosish va nafas nisbati qanday?',
    options: ['15:1', '20:2', '30:2', '10:1'],
    optionsUz: ['15:1', '20:2', '30:2', '10:1'],
    correctIndex: 2,
    explanation: 'При СЛР выполняется 30 нажатий на грудную клетку и 2 вдоха.',
    explanationUz: 'YOR da ko\'krak qafasiga 30 ta bosish va 2 ta nafas bajariladi.',
  },
  {
    id: 'first-aid-3',
    topicId: 'first-aid',
    question: 'Что делать при переломе конечности?',
    questionUz: 'Qo\'l-oyoq sinishida nima qilish kerak?',
    options: ['Вправить кость', 'Зафиксировать конечность', 'Растереть место перелома', 'Положить лёд'],
    optionsUz: ['Suyakni joyiga qo\'yish', 'Qo\'l-oyoqni qimirlatmaslik', 'Singan joyni ishqalash', 'Muz qo\'yish'],
    correctIndex: 1,
    explanation: 'При переломе необходимо зафиксировать (иммобилизировать) повреждённую конечность.',
    explanationUz: 'Sinishda shikastlangan qo\'l-oyoqni qimirlatmaydigan qilib mahkamlash (immobilizatsiya) kerak.',
  },

  // Ответственность
  {
    id: 'responsibility-1',
    topicId: 'responsibility',
    question: 'Какое наказание за управление в состоянии алкогольного опьянения?',
    questionUz: 'Mast holda boshqarish uchun qanday jazo?',
    options: ['Штраф', 'Лишение прав', 'Штраф и лишение прав', 'Предупреждение'],
    optionsUz: ['Jarima', 'Huquqdan mahrum qilish', 'Jarima va huquqdan mahrum qilish', 'Ogohlantirish'],
    correctIndex: 2,
    explanation: 'За управление ТС в состоянии опьянения грозит штраф и лишение права управления.',
    explanationUz: 'Mast holda TV boshqarganlik uchun jarima va boshqarish huquqidan mahrum qilish ko\'zda tutilgan.',
  },
  {
    id: 'responsibility-2',
    topicId: 'responsibility',
    question: 'Что грозит за оставление места ДТП?',
    questionUz: 'YTH joyini tark etganlik uchun nima tahdid qiladi?',
    options: ['Предупреждение', 'Штраф', 'Лишение прав или арест', 'Ничего'],
    optionsUz: ['Ogohlantirish', 'Jarima', 'Huquqdan mahrum qilish yoki hibsga olish', 'Hech narsa'],
    correctIndex: 2,
    explanation: 'За оставление места ДТП грозит лишение права управления или административный арест.',
    explanationUz: 'YTH joyini tark etganlik uchun boshqarish huquqidan mahrum qilish yoki ma\'muriy hibsga olish tahdid qiladi.',
  },

  // Дорожная разметка
  {
    id: 'marking-1',
    topicId: 'marking',
    question: 'Что означает сплошная линия разметки?',
    questionUz: 'Uzluksiz chiziq nima degani?',
    options: ['Можно пересекать', 'Запрещено пересекать', 'Рекомендация', 'Временная разметка'],
    optionsUz: ['Kesib o\'tish mumkin', 'Kesib o\'tish taqiqlangan', 'Tavsiya', 'Vaqtinchalik chiziq'],
    correctIndex: 1,
    explanation: 'Сплошную линию разметки пересекать запрещено.',
    explanationUz: 'Uzluksiz chiziqni kesib o\'tish taqiqlangan.',
  },
  {
    id: 'marking-2',
    topicId: 'marking',
    question: 'Что означает жёлтая разметка у края дороги?',
    questionUz: 'Yo\'l chetidagi sariq chiziq nima degani?',
    options: ['Парковка разрешена', 'Остановка запрещена', 'Главная дорога', 'Временная разметка'],
    optionsUz: ['Parkovka ruxsat', 'To\'xtash taqiqlangan', 'Asosiy yo\'l', 'Vaqtinchalik chiziq'],
    correctIndex: 1,
    explanation: 'Жёлтая сплошная линия у края дороги означает запрет остановки.',
    explanationUz: 'Yo\'l chetidagi sariq uzluksiz chiziq to\'xtash taqiqlanganligini bildiradi.',
  },
];
